### ISSUE TITLE
regl.party is offline

### ISSUE THREAD

**Issue by munrocket** [regl-project/regl-site#6]
`regl.party` is offline, please create site with free hosting on github pages, here [manual](https://guides.github.com/features/pages/)

**Comment by mootari** [comment]
@mikolalysenko I just bought the domain regl.party for the next 3 years (it was on sale). What is the IP of the Surge server where regl-site is currently hosted?

(In the meantime, an [archive.org version](http://web.archive.org/web/20190417190808/http://regl.party/) exists.)

**Comment by mootari** [comment]
Update:
- Found the IP (138.197.172.72) on the [cached version](https://webcache.googleusercontent.com/search?q=cache:41papRfxJYoJ:https://myip.ms/view/ip_addresses/138.197.172.72+&cd=3&hl=de&ct=clnk&gl=de) of a whois directory.
- Confirmed via ```curl -H Host:regl.party http://138.197.172.72``` that site is still online.
- Added A record.

Hopefully regl.party will be back up shortly.

**Comment by mootari** [comment]
Rejoice, it's back online! In celebration I've slapped two more years on top, i.e., the domain is secured until Sep 6, 2024.

@mikolalysenko Let me know if you want the domain transferred back to your own namecheap account.

**Comment by MaxBittker** [comment]
woo! thanks @mootari

**Comment by mootari** [comment]
I believe this issue can be closed?
